### ISSUE TITLE
Unclear on how username and password work

### ISSUE THREAD

**Issue by danalexilewis** [nabeix/gitlump#5]
Hey there, I have pulled down the repo on both a mac and pc and have had trouble getting authentication to work so I can access private repos. In the end I hard code added my personal token onto the end of the url lines in GitHubConnection.js

`url = this.requestURL(`users/${name}/repos?access_token=11111111111111111111111111111`);
 } else if (type === "org") {
 url = this.requestURL(`orgs/${name}/repos?access_token=11111111111111111111111111111`);`

which gave me the ability to do what I wanted. I saw the todo in the ts file saying that you would like to read this out of the gitlump.config file which I think is a great idea.

So this issue is more to do with how was the auth meant to work. I tried creating an inline json object based on the auth interface and that didn't work either... at a bit of a loss on how this was meant to work. cheers dan

**Comment by nabeix** [comment]
Hi,

Currently, auth prompt is shown when endpoint returns auth related status code.
It is meant to work for GitHub Enterprise API and has not taken account of github.com.
github.com returns `401 Unauthorized` when authenticating with **invalid credentials**.

To support github.com private repos, I have two plans.
- Read access token from an environment variable(e.g. `GITLUMP_GITHUB_TOKEN`)

The access token is generated and stored as an environment variable by the user.
gitlump reads this and send to the endpoint in `?access_token=` query(like your code) or `Authorization: token OAUTH-TOKEN` header.

I was thinking that store the token in `.gitlump.config` before.
But, it has security risk.
I think environment variables are good.
- Add option about basic authentication

github.com API supports basic authentication.
And when the authentication is successful, we can access the private repos information.
So, add option to `.gitlump.json` to enable always basic authentication.

**Comment by danalexilewis** [comment]
Ah right that makes so much more sense. I like the environment variables route - but to be honest I'd be just as happy with it being in a configuration file that is got ignored.

**Comment by nabeix** [comment]
> it being in a configuration file that is got ignored.

OK, I will add an option whether or not use of the access token.

**Comment by nabeix** [comment]
I released new version 0.0.4.
It supports access token by `useAccessToken` in `.gitlump.json`.
Please try it.

**Comment by danalexilewis** [comment]
Awesome - will do later today.

**Comment by danalexilewis** [comment]
nice - working good now and the updated documentation was way better. TY
